[package]
name = "neatrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
crossbeam = "0.8.2"
topo_sort = "0.4"

[build]
profiler = true
